### ISSUE TITLE
can't create obj/A_Instruction.o: No such file or directory

### ISSUE THREAD

**Issue by nicolast0604** [mariusmm/RISC-V-TLM#2]
root@ubuntu-s-4vcpu-8gb-sfo2-01:~/RISC-V-TLM# make
Compiling src/A_Instruction.cpp ...
Assembler messages:
Fatal error: can't create obj/A_Instruction.o: No such file or directory
Makefile:37: recipe for target 'obj/A_Instruction.o' failed
make: *** [obj/A_Instruction.o] Error 1

**Comment by mariusmm** [comment]
You need to create the obj directory

"mkdir obj"
