### ISSUE TITLE
Raised exception for all tests

### ISSUE THREAD

**Issue by AntonioGenov** [mariusmm/RISC-V-TLM#4]
**BUG DESCRIPTION**
I had no problems with the compilation, but when I try to start a .asm test I always receive an exception at the beginning of the simulation (the same for each .asm). I didn't tried the C and FreeRTOS ones. The only changes that I made was in the Makefile to declare my SYSTEMC_HOME and to change from c++11 to c++14.

**INFOs:**
 (Virtual Machine)
 - OS: Ubuntu 16.04.6 LTS

**COMPILATION AND OUTPUT**
`
~/Desktop/RISCV$ make
Compiling src/C_Instruction.cpp ...
Done!
Compiling src/Simulator.cpp ...
Done!
Compiling src/CPU.cpp ...
Done!
Compiling src/Timer.cpp ...
Done!
Compiling src/M_Instruction.cpp ...
Done!
Compiling src/Trace.cpp ...
Done!
Compiling src/Instruction.cpp ...
Done!
Compiling src/Log.cpp ...
Done!
Compiling src/Performance.cpp ...
Done!
Compiling src/Registers.cpp ...
Done!
Compiling src/A_Instruction.cpp ...
Done!
Compiling src/Memory.cpp ...
Done!
Compiling src/Execute.cpp ...
Done!
Compiling src/BusCtrl.cpp ...
Done!
Linking complete!

~/Downloads/RISC-V-TLM-master$ ./RISCV_TLM tests/asm/BasicLoop.asm 

        SystemC 2.3.3-Accellera --- Jul 23 2019 11:58:05
        Copyright (c) 1996-2018 by all Contributors,
        ALL RIGHTS RESERVED
LogLevel set to 0
No DMI access
************************************
Registers dump
x0 (zero):            0 x1 (ra):              0 x2 (sp):       67108863 x3 (gp):              0
x4 (tp):              0 x5 (t0):              0 x6 (t1):              0 x7 (t2):              0
x8 (s0/fp):           0 x9 (s1):              0 x10 (a0):             0 x11 (a1):             0
x12 (a2):             0 x13 (a3):             0 x14 (a4):             0 x15 (a5):             0
x16 (a6):             0 x17 (a7):             0 x18 (s2):             0 x19 (s3):             0
x20 (s4):             0 x21 (s5):             0 x22 (s6):             0 x23 (s7):             0
x24 (s8):             0 x25 (s9):             0 x26 (s10):            0 x27 (s11):            0
x28 (t3):             0 x29 (t4):             0 x30 (t5):             0 x31 (t6):             0
PC: 0x0
************************************
Simulation time 0 s
# data memory reads: 0
# data memory writes: 0
# code memory reads: 1
# code memory writes: 0
# registers read: 0
# registers write: 1
# instructions executed: 0

Error: Exception: Exception
In file: src/Execute.cpp:2171
In process: top.cpu.CPU_thread @ 0 s`

**Comment by mariusmm** [comment]
You are trying to start the simulator and run a .asm file, but you need to compile the source code for the example and get a .hex file.
In each test directory there is a Makefile for that. You will need the RISC-V toolchain ready in your system.

**Comment by AntonioGenov** [comment]
Okay thanks, 
Normally, I prepared the RISCV toolchain. 
I tried with Memoryacces.asm and BasicLoop.asm and here is what I have now:

`
~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-as Memoryaccess.asm -o Memoryaccess.o
~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-ld Memoryaccess.o -o Memoryaccess.elf
~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-objcopy -O ihex Memoryaccess.elf Memoryaccess.hex
~/Desktop/RISCV/tests/asm$ cd ../..
~/Desktop/RISCV$ make

Compiling src/C_Instruction.cpp ...
Done!
Compiling src/Simulator.cpp ...
Done!
Compiling src/CPU.cpp ...
Done!
Compiling src/Timer.cpp ...
Done!
Compiling src/M_Instruction.cpp ...
Done!
Compiling src/Trace.cpp ...
Done!
Compiling src/Instruction.cpp ...
Done!
Compiling src/Log.cpp ...
Done!
Compiling src/Performance.cpp ...
Done!
Compiling src/Registers.cpp ...
Done!
Compiling src/A_Instruction.cpp ...
Done!
Compiling src/Memory.cpp ...
Done!
Compiling src/Execute.cpp ...
Done!
Compiling src/BusCtrl.cpp ...
Done!
Linking complete!

~/Desktop/RISCV$ ./RISCV_TLM tests/asm/Memoryaccess.hex 

        SystemC 2.3.3-Accellera --- Jul 23 2019 11:58:05
        Copyright (c) 1996-2018 by all Contributors,
        ALL RIGHTS RESERVED
LogLevel set to 0
02 extended address 0x10000
03 PC set to 0x10078
No DMI access
Wrong instruction
0x0afe3031b

************************************
Registers dump
x0 (zero):            0 x1 (ra):              0 x2 (sp):       67108863 x3 (gp):              0
x4 (tp):              0 x5 (t0):              0 x6 (t1):          53248 x7 (t2):              0
x8 (s0/fp):           0 x9 (s1):              0 x10 (a0):             0 x11 (a1):             0
x12 (a2):             0 x13 (a3):             0 x14 (a4):             0 x15 (a5):             0
x16 (a6):             0 x17 (a7):             0 x18 (s2):             0 x19 (s3):             0
x20 (s4):             0 x21 (s5):             0 x22 (s6):             0 x23 (s7):             0
x24 (s8):             0 x25 (s9):             0 x26 (s10):            0 x27 (s11):            0
x28 (t3):             0 x29 (t4):             0 x30 (t5):             0 x31 (t6):             0
PC: 0x1007c
************************************
Simulation time 10 ns
# data memory reads: 0
# data memory writes: 0
# code memory reads: 2
# code memory writes: 0
# registers read: 0
# registers write: 2
# instructions executed: 1

Error: Execute: NOP
In file: src/Execute.cpp:2088
In process: top.cpu.CPU_thread @ 10 ns

~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-as BasicLoop.asm -o BasicLoop.o
~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-ld BasicLoop.o -o BasicLoop.elf
~/Desktop/RISCV/tests/asm$ riscv64-unknown-linux-gnu-objcopy -O ihex BasicLoop.elf BasicLoop.hex
~/Desktop/RISCV/tests/asm$ cd ../.. 
~/Desktop/RISCV$ ./RISCV_TLM tests/asm/BasicLoop.hex 

        SystemC 2.3.3-Accellera --- Jul 23 2019 11:58:05
        Copyright (c) 1996-2018 by all Contributors,
        ALL RIGHTS RESERVED
LogLevel set to 0
02 extended address 0x10000
03 PC set to 0x10078
No DMI access
************************************
Registers dump
x0 (zero):            0 x1 (ra):              0 x2 (sp):       67108863 x3 (gp):              0
x4 (tp):              0 x5 (t0):              0 x6 (t1):              0 x7 (t2):              1
x8 (s0/fp):           0 x9 (s1):              0 x10 (a0):             0 x11 (a1):             0
x12 (a2):             0 x13 (a3):             0 x14 (a4):             0 x15 (a5):             0
x16 (a6):             0 x17 (a7):             0 x18 (s2):             0 x19 (s3):             0
x20 (s4):             0 x21 (s5):             0 x22 (s6):             0 x23 (s7):             0
x24 (s8):             0 x25 (s9):             0 x26 (s10):            0 x27 (s11):            0
x28 (t3):             0 x29 (t4):             0 x30 (t5):             0 x31 (t6):             0
PC: 0x0
************************************
Simulation time 220 ns
# data memory reads: 0
# data memory writes: 0
# code memory reads: 23
# code memory writes: 0
# registers read: 42
# registers write: 13
# instructions executed: 22

Error: Exception: Exception
In file: src/Execute.cpp:2171
In process: top.cpu.CPU_thread @ 220 ns
`

**Comment by mariusmm** [comment]
Hello,

it seems that you are compiling for a RISCV 64 bits, but the simulator is for 32bit only. Can you check that?
