### ISSUE TITLE
Some c tests' Makefile failure 

### ISSUE THREAD

**Issue by ROOCKIET** [mariusmm/RISC-V-TLM#5]
Some C tests programs make fillure.

Such as tests/c/func2, $make directly:
 
**riscv32-unknown-linux-gnu-objdump -d func2.o > dump
/bin/sh: 1: riscv32-unknown-linux-gnu-objdump: not found
Makefile:32: recipe for target 'func2' failed
make: *** [func2] Error 127**

After changed 'riscv32-unknown-linux-gnu-objdump' in the makefile to 'riscv32-unknown-elf-objdump',  success to obtain 'func2.hex'.

The method is right or wrong?

Thanks.

**Comment by mariusmm** [comment]
Hello Roockiet,

you're right, Makefile in some of the tests are wrong and your solutions is fine.

I'll commit a fixed version ASAP.

Cheers,
Màrius
