### ISSUE TITLE
'Error Exception'when run .hex files which translated from .asm files

### ISSUE THREAD

**Issue by ROOCKIET** [mariusmm/RISC-V-TLM#7]
Hello,
Followed the ‘readme’，in tsets/asm/ , I translated .asm files to 0.hex file, while run the simulator, there will be an 'Error Exception',:

**Error: Exception: Exception
In file: src/extension_base.cpp:58**

I fixed it by add ‘ecall’ instruction at the bottom line in the .asm files.

**Comment by mariusmm** [comment]
Thank you @ROOCKIET , I'll add ecall instruction at the end of each asm example
